name: "Jira Issue Integration"
description: "Jira Issue Integration"
author: "Bo-Yi Wu"
inputs:
  base_url:
    description: "Base URL of Jira"
  insecure:
    description: "Insecure for SSL"
  username:
    description: "username for Basic authentication. This method is only recommended for tools like scripts or bots."
  password:
    description: "password for Basic authentication. This method is only recommended for tools like scripts or bots."
  token:
    description: "Personal access token (PAT). This method incorporates the user account in the access token."
  ref:
    description: "The fully-formed ref of the branch or tag that triggered the workflow run"
  issue_format:
    description: "matches string that references to an alphanumeric issue, e.g. ABC-1234"
    default: "([A-Z]{1,10}-[1-9][0-9]*)"
  transition:
    description: "move issue to a specific status, e.g. Done, Start Progress"
  resolution:
    description: "set resolution of issue, e.g. Done, Fixed"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "cloud"
  color: "blue"
